[build]
default-target = "arm-unknown-linux-gnueabi" # e.g. Raspberry Pi Zero W

[target.arm-unknown-linux-gnueabi.dockerfile]
file = "cross/docker/Dockerfile.arm-unknown-linux-gnueabi"
context = "cross/docker"
