[default]
permissions = ["allow-start", "allow-stop", "allow-open-devtools"]

[[permission]]
identifier = "allow-start"
description = "Allow invoking the start command"
commands.allow = ["start"]

[[permission]]
identifier = "allow-stop"
description = "Allow invoking the stop command"
commands.allow = ["stop"]

[[permission]]
identifier = "allow-open-devtools"
description = "Allow invoking the open_devtools command (debug builds only)"
commands.allow = ["open_devtools"]
